"""Identity application ports and errors."""

from workflowforge_application.identity.authentication import (
    AuthenticatedUser,
    AuthenticateUser,
    AuthenticateUserCommand,
    SetUserPassword,
    SetUserPasswordCommand,
)
from workflowforge_application.identity.credentials import PasswordCredential
from workflowforge_application.identity.errors import (
    DuplicateNormalizedEmailError,
    DuplicateOrganizationMembershipError,
    DuplicateOrganizationSlugError,
    DuplicatePasswordCredentialError,
    DuplicateRefreshTokenDigestError,
    IdentityApplicationError,
    InvalidCredentialsError,
    InvalidPasswordError,
    MalformedStoredCredentialError,
    MissingIdentityReferenceError,
    RefreshRotationConflictError,
    SessionExpiredError,
    SessionNotFoundError,
    SessionRevokedError,
    UserAuthenticationDisabledError,
)
from workflowforge_application.identity.ports import (
    MembershipRepository,
    OrganizationRepository,
    PasswordCredentialRepository,
    PasswordHasher,
    RefreshTokenHasher,
    SessionRepository,
    UserRepository,
)

__all__ = [
    "AuthenticateUser",
    "AuthenticateUserCommand",
    "AuthenticatedUser",
    "DuplicateNormalizedEmailError",
    "DuplicateOrganizationMembershipError",
    "DuplicateOrganizationSlugError",
    "DuplicatePasswordCredentialError",
    "DuplicateRefreshTokenDigestError",
    "IdentityApplicationError",
    "InvalidCredentialsError",
    "InvalidPasswordError",
    "MalformedStoredCredentialError",
    "MembershipRepository",
    "MissingIdentityReferenceError",
    "OrganizationRepository",
    "PasswordCredential",
    "PasswordCredentialRepository",
    "PasswordHasher",
    "RefreshTokenHasher",
    "RefreshRotationConflictError",
    "SetUserPassword",
    "SetUserPasswordCommand",
    "SessionExpiredError",
    "SessionNotFoundError",
    "SessionRepository",
    "SessionRevokedError",
    "UserAuthenticationDisabledError",
    "UserRepository",
]
